-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgfB6z7KgBi3PhSV3k
lNIYJhyXcwaLPJVnMuYdWRwz7fegCgYIKoZIzj0DAQehRANCAAQ5FnT3VIWChIGJ
9nsSQb3mKGWIsG+Ij37O78vH/XGEJPM8sglITAWfBbogurMnsgn6LHHYw3dhxLxX
2d3xaGM9
-----END PRIVATE KEY-----